[tool.poetry]
name = "{{cookiecutter.repository_name}}"
version = "0.0.1"
description = "{{cookiecutter.repository_description}}"
authors = ["{{cookiecutter.author_name}}"]

[tool.poetry.dependencies]
python = "3.9.13"

[tool.poetry.dev-dependencies]
notebook = "^6.4.10"
pre-commit = "^2.17.0"