[tool.poetry]
name = "{{cookiecutter.directory_name}}"
version = "0.1.0"
description = "{{cookiecutter.description}}"
authors = ["{{cookiecutter.author_name}}"]

[tool.poetry.dependencies]
python = "^3.8"
notebook = "^6.4.10"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"